# Generated by Django 5.0.3 on 2024-03-24 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Legislator",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                (
                    "primary_sponsor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vote_manager.legislator",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vote_manager.bill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoteResult",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("vote_type", models.IntegerField()),
                (
                    "legislator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vote_manager.legislator",
                    ),
                ),
                (
                    "vote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vote_manager.vote",
                    ),
                ),
            ],
        ),
    ]
